"""Creacion inicial de las tablas de la base de datos

Revision ID: 8100462da76f
Revises: 
Create Date: 2026-04-17 19:13:32.421215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8100462da76f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('id_equipo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url_logo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.create_table('torneo',
    sa.Column('id_torneo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('Liga', 'Eliminatoria', name='tipo_torneo'), nullable=False),
    sa.Column('fechas', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_torneo')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('Admin', 'User', name='rol_types'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clasificacion',
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('pj', sa.Integer(), nullable=True),
    sa.Column('pg', sa.Integer(), nullable=True),
    sa.Column('pe', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneo.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_torneo', 'id_equipo')
    )
    op.create_table('partido',
    sa.Column('id_partido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('id_local', sa.Integer(), nullable=False),
    sa.Column('id_visitante', sa.Integer(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visit', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Fin', name='estado_partido'), nullable=False),
    sa.ForeignKeyConstraint(['id_local'], ['equipo.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneo.id_torneo'], ),
    sa.ForeignKeyConstraint(['id_visitante'], ['equipo.id_equipo'], ),
    sa.PrimaryKeyConstraint('id_partido')
    )
    op.create_table('pertenece',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_equipo')
    )
    op.create_table('stats_jugador',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('goles', sa.Integer(), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneo.id_torneo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_torneo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_jugador')
    op.drop_table('pertenece')
    op.drop_table('partido')
    op.drop_table('clasificacion')
    op.drop_table('usuario')
    op.drop_table('torneo')
    op.drop_table('equipo')
    # ### end Alembic commands ###
