"""Añadido el campo fecha a la tabla partido

Revision ID: bf115f234fc5
Revises: d6939a0f6f27
Create Date: 2026-04-18 00:48:04.905582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf115f234fc5'
down_revision = 'd6939a0f6f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
